"""Stage and package the authoritative pygame game for WebAssembly."""

from __future__ import annotations

import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import time
import zipfile

from .runtime_assets import asset_dir

ROOT = Path(__file__).resolve().parents[2]
RUNTIME_ASSET_DIRS = ("audio", "bosses", "characters", "items", "tiles", "ui", "character-packs", "character-creation")
WEB_BACKGROUNDS = ("corrupted", "cow")
CHARACTER_CONTROLS = '''
<style>
html,body{overflow-x:hidden!important;overflow-y:auto!important;min-height:calc(100vh + 340px)}
#canvas{position:fixed!important;inset:0!important;margin:auto!important;width:100vw!important;height:100vh!important;object-fit:contain;background:#000}
#character-tools{position:relative;top:100vh;z-index:10}
html.omega-character-tools-hidden,html.omega-character-tools-hidden body{min-height:100vh!important;overflow:hidden!important}
html.omega-character-tools-hidden #character-tools{display:none!important}
#character-tools-close{position:absolute;top:8px;right:10px;width:32px;height:32px;border:0;border-radius:8px;background:#2a2e3f;color:#c0caf5;font:22px/1 system-ui;cursor:pointer}
#character-tools-close:hover{background:#414868}
</style>
<section id="character-tools" aria-label="Custom characters" style="max-width:850px;margin:20px auto;padding:18px;text-align:left;font:16px system-ui;color:#c0caf5;background:#1a1b26;border:1px solid #414868;border-radius:12px">
<button type="button" id="character-tools-close" aria-label="Hide custom character tools">×</button>
<strong>Make the protagonist yours.</strong>
<p>Choose David, The Omarch King, or The Omarch Queen during setup. For a custom character, give the agent kit to your image-capable agent, then import its finished ZIP.</p>
<a href="character-agent-kit.zip" download style="color:#9ece6a">Download agent kit</a>
<label style="margin-left:24px;color:#7dcfff">Import character ZIP <input id="character-import" type="file" accept=".zip,application/zip" style="display:block;margin-top:12px"></label>
<p id="character-import-status" role="status">Imports stay in this browser. Keep a copy of your ZIP.</p>
</section>
<script>
// Returning focus to play restores its full viewport after using import tools.
// SDL captures wheel/keyboard scrolling, so the canvas itself must restore it.
const gameCanvas = document.getElementById('canvas');
gameCanvas.addEventListener('focus', () => window.scrollTo(0, 0));
gameCanvas.addEventListener('pointerdown', () => window.scrollTo(0, 0));
// Let SDL receive the credit shortcuts instead of browser fullscreen/devtools.
window.addEventListener('keydown', (event) => {
  if (document.activeElement === gameCanvas && (event.key === 'F11' || event.key === 'F12')) {
    event.preventDefault();
  }
}, {capture: true});
window.omegaCharacterImport = '';
window.omegaCharacterImportStatus = '';
(function () {
  const tools = document.getElementById('character-tools');
  const close = document.getElementById('character-tools-close');
  const hide = () => {
    document.documentElement.classList.add('omega-character-tools-hidden');
    try { sessionStorage.setItem('omega-hide-character-tools', '1'); } catch (error) {}
    window.scrollTo(0, 0);
    if (gameCanvas) gameCanvas.focus();
  };
  try {
    if (sessionStorage.getItem('omega-hide-character-tools') === '1') hide();
  } catch (error) {}
  if (close) close.addEventListener('click', hide);
})();
document.getElementById('character-import').addEventListener('change', function () {
  const file = this.files[0];
  if (!file) return;
  if (file.size > 4194304) { window.omegaCharacterImportStatus = 'Choose a character ZIP under 4 MiB.'; return; }
  window.omegaCharacterImportStatus = 'Reading character ZIP…';
  const reader = new FileReader();
  reader.onload = () => {
    window.omegaCharacterImport = String(reader.result).split(',')[1];
    window.omegaCharacterImportStatus = 'Validating character; start the game if it has not loaded yet…';
  };
  reader.onerror = () => { window.omegaCharacterImportStatus = 'Could not read the ZIP.'; };
  reader.readAsDataURL(file);
  this.value = '';
});
setInterval(() => {
  if (window.omegaCharacterImportStatus) document.getElementById('character-import-status').textContent = window.omegaCharacterImportStatus;
}, 250);
</script>
'''
WEB_MAIN = '''"""Omega Omarchy WebAssembly entry point; generated by ./scripts/omega web."""

import asyncio
import pygame  # pygbag preloader marker; runtime code also imports pygame

from omega_omarchy.app import run_game_async


async def main():
    try:
        await run_game_async(seed=__SEED__)
    except Exception:
        import traceback
        from platform import window
        window.console.error(traceback.format_exc())
        window.omegaCharacterImportStatus = "The game could not start. Reload the page; the browser console has details."
        raise


asyncio.run(main())
'''


def _replace_directory(dest: Path) -> None:
    resolved = dest.resolve()
    protected = {Path("/"), Path.home().resolve(), ROOT.resolve(), ROOT.parent.resolve()}
    if resolved in protected or dest.is_symlink():
        raise ValueError(f"refusing to replace unsafe web output directory: {dest}")
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)


def _replace_required(source: str, old: str, new: str, *, label: str) -> str:
    if old not in source:
        raise RuntimeError(f"pygbag launcher changed: missing {label}")
    return source.replace(old, new, 1)


def stage_web(stage: Path, *, seed: str = "omega-fixture-1", character_packs: tuple[Path, ...] = ()) -> Path:
    """Create the real Chapter 1 app without later-zone or source masters."""

    stage = Path(stage)
    _replace_directory(stage)
    package_source = ROOT / "src" / "omega_omarchy"
    shutil.copytree(
        package_source,
        stage / "omega_omarchy",
        ignore=shutil.ignore_patterns(
            "level_editor.py",
            "__pycache__",
            "*.pyc",
            "assets.py",
            "character_build.py",
            "refinement_art.py",
            "audio_build.py",
            "credits_build.py",
            "chiptune.py",
            "music_diagnostic.py",
            "spritekit.py",
            "cli.py",
            "web_build.py",
            "__main__.py",
        ),
    )
    try:
        revision = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, text=True
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        revision = "unknown"
    (stage / "omega_omarchy" / "_build_revision.py").write_text(
        f'REVISION = "{revision}"\n',
        encoding="utf-8",
    )
    runtime_assets = stage / "assets"
    runtime_assets.mkdir()
    source_assets = asset_dir()
    for name in RUNTIME_ASSET_DIRS:
        shutil.copytree(source_assets / name, runtime_assets / name)
    from .character_pack import validate_pack as validate_character

    for pack in character_packs:
        record = validate_character(pack)
        target = runtime_assets / "character-packs" / record["id"]
        if target.exists():
            raise ValueError(f"Character id already bundled: {record['id']}")
        target.mkdir()
        for relative in ["manifest.json", *record["files"]]:
            destination = target / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(pack / relative, destination)
    for fidelity in ("sixteen-bit", "high", "ultra"):
        source_fidelity = source_assets / "fidelity" / fidelity
        dest_fidelity = runtime_assets / "fidelity" / fidelity
        for name in ("bosses", "characters", "effects", "enemies", "items", "tiles", "ui"):
            shutil.copytree(source_fidelity / name, dest_fidelity / name)
        for palette in WEB_BACKGROUNDS:
            shutil.copytree(
                source_fidelity / "bg" / palette,
                dest_fidelity / "bg" / palette,
            )
    icon = source_assets / "ui" / "omega-omarchy-icon-256.png"
    shutil.copyfile(icon, stage / "favicon.png")
    (stage / "main.py").write_text(
        WEB_MAIN.replace("__SEED__", repr(str(seed))), encoding="utf-8"
    )
    return stage


def _normalize_mtimes(root: Path) -> None:
    """Keep the packaged archive stable across contributor machines."""

    epoch = int(os.environ.get("SOURCE_DATE_EPOCH", "1704067200"))
    for path in sorted(root.rglob("*")):
        if path.is_file():
            os.utime(path, (epoch, epoch))


def _archive_timestamp() -> tuple[int, int, int, int, int, int]:
    epoch = int(os.environ.get("SOURCE_DATE_EPOCH", "1704067200"))
    return time.gmtime(epoch)[:6]


def _encode_web_audio(stage: Path) -> None:
    """Install browser-safe Ogg cues and reject accidental source masters."""

    dest = stage / "assets" / "audio"
    source_audio = asset_dir() / "audio"
    ffmpeg = None
    for source in sorted(dest.glob("*.wav")):
        target = source.with_suffix(".ogg")
        committed = source_audio / target.name
        if committed.is_file():
            shutil.copyfile(committed, target)
            source.unlink()
            continue
        if ffmpeg is None:
            ffmpeg = shutil.which("ffmpeg")
        if ffmpeg is None:
            raise RuntimeError("web packaging requires ffmpeg for browser-safe audio")
        process = subprocess.run(
            [
                ffmpeg,
                "-nostdin",
                "-hide_banner",
                "-loglevel",
                "error",
                "-y",
                "-i",
                str(source),
                "-map_metadata",
                "-1",
                "-fflags",
                "+bitexact",
                "-flags:a",
                "+bitexact",
                "-codec:a",
                "libvorbis",
                "-q:a",
                "5",
                str(target),
            ],
            check=False,
            capture_output=True,
            text=True,
        )
        if process.returncode:
            raise RuntimeError(f"could not encode {source.name}: {process.stderr.strip()}")
        source.unlink()
    # Tiered runtime files are committed Oggs. Never let a new source/master
    # format quietly inflate or break the browser package.
    forbidden = sorted(
        path for path in dest.rglob("*") if path.is_file() and path.suffix.lower() in {".wav", ".flac", ".mp4"}
    )
    if forbidden:
        names = ", ".join(path.relative_to(dest).as_posix() for path in forbidden[:5])
        raise RuntimeError(f"browser audio contains non-runtime masters: {names}")


def _store_web_archive(apk: Path) -> None:
    """Rewrite the pygbag archive as a stored ZIP with stable metadata.

    PNG and Ogg assets barely shrink under a second compression pass, while
    inflating hundreds of entries in CPython/WebAssembly can stall startup.
    Rebuilding ZipInfo (instead of copying pygbag's) keeps the bytes stable
    across encoder hosts so ``git diff -- assets dist/web`` can pass in CI.
    """

    stamp = _archive_timestamp()
    replacement = apk.with_suffix(".stored.apk")
    with zipfile.ZipFile(apk, "r") as source, zipfile.ZipFile(
        replacement, "w", compression=zipfile.ZIP_STORED
    ) as target:
        for member in sorted(source.infolist(), key=lambda item: item.filename):
            payload = source.read(member.filename)
            info = zipfile.ZipInfo(filename=member.filename, date_time=stamp)
            info.compress_type = zipfile.ZIP_STORED
            info.create_system = 3
            directory = member.is_dir() or member.filename.endswith("/")
            info.external_attr = (0o755 if directory else 0o644) << 16
            target.writestr(info, payload)
    replacement.replace(apk)


def _repair_pygbag_launcher(built: Path) -> None:
    """Pin BrowserFS, select the fast stored archive, and theme startup.

    pygbag 0.9.3's default template refers to a BrowserFS URL that currently
    returns 404. Loading the pinned compatible script before pythons.js avoids
    the upstream startup stall and keeps the workaround visible and removable.
    """

    vendor = ROOT / "vendor" / "browserfs-1.4.3"
    shutil.copyfile(vendor / "browserfs.min.js", built / "browserfs.min.js")
    shutil.copyfile(vendor / "LICENSE", built / "BROWSERFS-LICENSE.txt")
    index = built / "index.html"
    html = index.read_text(encoding="utf-8")
    early_loader = '<script src="browserfs.min.js"></script>\n'
    if not html.startswith(early_loader):
        html = early_loader + html
    html, browserfs_replacements = re.subn(
        r'<script src="https://pygame-web\.github\.io/[^\"]+/browserfs\.min\.js"></script>',
        "<!-- BrowserFS is pinned and loaded before the WebAssembly runtime. -->",
        html,
    )
    if browserfs_replacements != 1:
        raise RuntimeError("pygbag launcher changed: expected one BrowserFS reference")
    html = _replace_required(
        html,
        "if platform.window.location.host.find('.itch.zone')>0:",
        "if True:  # the build replaces this with a stored ZIP",
        label="archive selection",
    )
    html = _replace_required(
        html, "appdir.mkdir()", "appdir.mkdir(exist_ok=True)", label="app directory creation"
    )
    html = _replace_required(
        html,
        "    # unpack filesystem from compressed archive into work dir",
        '    platform.window.console.log("[omega-web] unpack start")\n\n'
        "    # unpack filesystem from compressed archive into work dir",
        label="unpack milestone",
    )
    html = _replace_required(
        html,
        "    # preloader will change to work dir and prepend it to sys.path",
        '    platform.window.console.log("[omega-web] unpack complete")\n\n'
        "    # preloader will change to work dir and prepend it to sys.path",
        label="preloader call",
    )
    html = _replace_required(
        html,
        "    # wait preloading complete : that includes images and wasm compilation of bundled modules",
        '    platform.window.console.log("[omega-web] preloader started")\n\n'
        "    # wait preloading complete : that includes images and wasm compilation of bundled modules",
        label="preloader wait",
    )
    html = _replace_required(
        html,
        "    await shell.source(main, callback=ui_callback)",
        '    platform.window.console.log("[omega-web] application start")\n'
        "    import aio.pep0723\n"
        '    await aio.pep0723.pip_install("pygame")\n'
        '    platform.window.console.log("[omega-web] pygame ready")\n'
        '    namespace = {"__name__": "__main__", "__file__": str(main)}\n'
        '    exec(compile(main.read_text(), str(main), "exec"), namespace)',
        label="application loader",
    )
    html = html.replace('#7f7f7f', '#0e0e14').replace(
        "background-color:powderblue;", "background-color:#0e0e14;"
    )
    html = html.replace(
        "background: green;\n            color: blue;",
        "background: #1a1b26;\n            color: #b9f27c;\n            border: 1px solid #9ece6a;",
    )
    from .release import release_label

    html = _replace_required(
        html,
        '<div id="infobox">Loading, please wait ...</div>',
        f'<div id="infobox">Loading Omega Omarchy {release_label()} …</div>',
        label="loading banner",
    )
    index.write_text(html, encoding="utf-8")
    tarball = built / "omega-omarchy.tar.gz"
    if tarball.exists():
        tarball.unlink()


def build_web(dest: Path, *, seed: str = "omega-fixture-1", character_packs: tuple[Path, ...] = ()) -> Path:
    """Build a deployable pygbag artifact containing the real game."""

    from .credits_build import build_credits

    dest = Path(dest)
    stage = ROOT / "build" / "web-stage" / "omega-omarchy"
    stage_web(stage, seed=seed, character_packs=character_packs)
    build_credits(target=stage / "omega_omarchy/data/credits.json")
    _encode_web_audio(stage)
    _normalize_mtimes(stage)
    command = [
        sys.executable,
        "-m",
        "pygbag",
        "--build",
        "--no_opt",
        "--ume_block",
        "0",
        "--width",
        "1280",
        "--height",
        "720",
        "--app_name",
        "Omega Omarchy",
        "--package",
        "org.omarchy.omega",
        "--title",
        "Omega Omarchy",
        "--icon",
        str(stage / "favicon.png"),
        str(stage),
    ]
    try:
        process = subprocess.run(
            command, cwd=ROOT, check=False, capture_output=True, text=True
        )
        if process.returncode:
            detail = (process.stdout + process.stderr)[-6000:]
            raise RuntimeError(detail.strip())
    except (OSError, subprocess.CalledProcessError) as exc:
        raise RuntimeError(
            "web packaging failed; install requirements/ci.txt and retry ./scripts/omega web"
        ) from exc
    built = stage / "build" / "web"
    if not (built / "index.html").is_file() or not (built / "omega-omarchy.apk").is_file():
        raise RuntimeError("pygbag did not produce the expected web application")
    _store_web_archive(built / "omega-omarchy.apk")
    _repair_pygbag_launcher(built)
    _replace_directory(dest)
    shutil.copytree(built, dest, dirs_exist_ok=True)
    shutil.copyfile(asset_dir() / "character-creation/agent-kit.zip", dest / "character-agent-kit.zip")
    with (dest / "index.html").open("a", encoding="utf-8") as page:
        page.write(CHARACTER_CONTROLS)
    shutil.copyfile(stage / "favicon.png", dest / "omega-omarchy-icon.png")
    (dest / "README.txt").write_text(
        "Omega Omarchy browser alpha: the authoritative simulation and renderer.\n"
        "Serve this directory over HTTP; opening index.html as a file will not work.\n"
        "It contains the Chapter 1 and Cow Level art; later development chapters are native-only.\n"
        "The launcher downloads the pinned pygbag 0.9.3 WebAssembly runtime.\n",
        encoding="utf-8",
    )
    return dest
